version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=sqlite:///data/lifeguards.db
    volumes:
      - ./backend/app:/app/app
      - ./data:/data
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
